Support host side syslog rate limit configuration
Junchao-Mellanox/sonic-host-services pull request #1
Opened 2022-10-12 03:27 UTC by Junchao-Mellanox

2022-10-13 03:21 UTC, keboliu approved these changes

2022-10-17 17:36 UTC, nazariig commented on scripts/hostcfgd
> +            return
@Junchao-Mellanox do we need a log message here?

2022-10-17 17:39 UTC, nazariig commented on scripts/hostcfgd
> +        cur_interval, cur_burst = self.parse_syslog_conf()
@Junchao-Mellanox suggest to have:
```python
new_interval = '0'
new_burst = '0'

if data:
    new_interval = data.get(self.SYSLOG_RATE_LIMIT_INTERVAL, '0')
    new_burst = data.get(self.SYSLOG_RATE_LIMIT_BURST, '0')
```

2022-10-17 17:42 UTC, nazariig commented on scripts/hostcfgd
> +    def parse_syslog_conf(self):
@Junchao-Mellanox why need to parse each time on Config DB update?

2022-10-21 06:47 UTC, Junchao-Mellanox commented
Hi @nazariig , could you please review again?

2022-10-24 14:29 UTC, nazariig requested changes

2022-10-24 14:29 UTC, nazariig commented on scripts/hostcfgd
> +        self.parse_syslog_conf()
@Junchao-Mellanox why not having it in constructor since the `hostcfgd` is guaranteed to be started after `rsyslog-config`?

2022-10-24 14:29 UTC, nazariig commented on scripts/hostcfgd
> +        run_cmd('systemctl restart rsyslog-config')
@Junchao-Mellanox will it print the error log to the syslog if any?

2022-10-24 14:29 UTC, nazariig commented on scripts/hostcfgd
> +    def syslog_handler(self, key, op, data):
@Junchao-Mellanox do we support global/partial configuration removal (e.g., OP = DEL_COMMAND)? From the implementation it looks so... And the same question for container side?

2022-10-25 11:51 UTC, Junchao-Mellanox commented on scripts/hostcfgd
> +    def syslog_handler(self, key, op, data):
No, we don't

2022-10-25 11:55 UTC, nazariig commented on scripts/hostcfgd
> +    def syslog_handler(self, key, op, data):
@Junchao-Mellanox so need to handle it properly in both HLD/code

2022-10-25 12:02 UTC, nazariig approved these changes

2022-10-25 13:14 UTC, closed without merging